name: LHCI-assert-netlify-on-budget-notification
on: pull_request
jobs:
  # This pass/fails a build with a budgets.json.
  assert-on-budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on Netlify urls and validate with budgets.json
        uses: ./
        with:
          urls: |
            https://practical-allen-be16f3.netlify.com
            https://practical-allen-be16f3.netlify.com/products/
            https://practical-allen-be16f3.netlify.com/contact/
          netlifySite: 'practical-allen-be16f3.netlify.com'
          budgetPath: '.github/lighthouse/budget.json'
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          applicationGithubToken: ${{ secrets.GITHUB_TOKEN }}
          personalGithubToken: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          logLevel: 'error'